version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"               
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(ci)"
    assignees:
      - "mqxym"
    target-branch: mqxym/dev
