name: Source Pull + Docker build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: "ghcr.io/"
      SOURCE_REPOSITORY: "https://github.com/"
      SOURCE_REPOSITORY_TAG: "1.0.0"
      SOURCE_REPOSITORY_BRANCH: "dev"
      SOURCE_REPOSITORY_ACCESS_PAT: "public"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY_PROD }}:${{ github.run_number }} -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY_PROD }}:latest -f docker/Dockerfile .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY_PROD }}:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY_PROD }}:latest
