# .github/workflows/docker-build.yml

name: Source Pull + Docker Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: "ghcr.io"
  SOURCE_REPOSITORY: "owner/source-repo"
  SOURCE_REF: "main"
  SOURCE_DIRECTORY: "public"
  IMAGE_NAME: "my-nginx-image"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v5

      - name: Checkout Source Repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          ref: ${{ env.SOURCE_REF }}
          path: ./source
          ssh-key: ${{ secrets.SOURCE_DEPLOYMENT_KEY || '' }}

      - name: Remove Git metadata
        run: rm -rf source/.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker Tag
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.SOURCE_REF }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          build-args: |
            SOURCE_DIRECTORY=${{ env.SOURCE_DIRECTORY }}
